# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb598ec563c1e9c120f086556979513862433314e2db2bdce0380d4d694302539fe16c38f901b133758b3ed790484d63abf1610df30a27efe8a55438bbc5688d

test:
  secret_key_base: 97d94d6b7db1f1927f962a0f568e7d1b99038920c47c4ca2664ca0e2376972ed53bde03c08e06925e36674240c7e50fa5271a8a77dcbe7cb196b0a2244dc08fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
